// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetExePath() {
  return window['go']['main']['App']['GetExePath']();
}

export function GetFileName() {
  return window['go']['main']['App']['GetFileName']();
}

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function GetStartupFile() {
  return window['go']['main']['App']['GetStartupFile']();
}

export function IsFileAssociationSet() {
  return window['go']['main']['App']['IsFileAssociationSet']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileAndUpdateWatch(arg1) {
  return window['go']['main']['App']['ReadFileAndUpdateWatch'](arg1);
}

export function ReadImageAsBase64(arg1) {
  return window['go']['main']['App']['ReadImageAsBase64'](arg1);
}

export function RegisterFileAssociation() {
  return window['go']['main']['App']['RegisterFileAssociation']();
}

export function ResolveImagePath(arg1) {
  return window['go']['main']['App']['ResolveImagePath'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SetStartupArg(arg1) {
  return window['go']['main']['App']['SetStartupArg'](arg1);
}

export function StartFileWatch() {
  return window['go']['main']['App']['StartFileWatch']();
}

export function StopFileWatch() {
  return window['go']['main']['App']['StopFileWatch']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
