// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildFileWorkspace(arg1:Array<string>):Promise<main.FileWorkspace>;

export function FormatMarkdownWithAI(arg1:main.AIFormatRequest):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetExePath():Promise<string>;

export function GetFileName():Promise<string>;

export function GetFilePath():Promise<string>;

export function GetStartupFile():Promise<string>;

export function IsFileAssociationSet():Promise<boolean>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenFilesDialog():Promise<Array<string>>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileAndUpdateWatch(arg1:string):Promise<string>;

export function ReadImageAsBase64(arg1:string):Promise<string>;

export function RegisterFileAssociation():Promise<void>;

export function ResolveImagePath(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SetStartupArg(arg1:string):Promise<void>;

export function StartFileWatch():Promise<void>;

export function StopFileWatch():Promise<void>;

export function TestAIModel(arg1:main.AIModelConfig):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
