// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion():Promise<string>;

export function GetExePath():Promise<string>;

export function GetFileName():Promise<string>;

export function GetFilePath():Promise<string>;

export function GetStartupFile():Promise<string>;

export function IsFileAssociationSet():Promise<boolean>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileAndUpdateWatch(arg1:string):Promise<string>;

export function ReadImageAsBase64(arg1:string):Promise<string>;

export function RegisterFileAssociation():Promise<void>;

export function ResolveImagePath(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SetStartupArg(arg1:string):Promise<void>;

export function StartFileWatch():Promise<void>;

export function StopFileWatch():Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
